// Default configuration (the HTML page can override it with window.OFFICE_CONFIG).
export const DEFAULT_CONFIG = {
  company: 'Balão da Informática',
  president: { name: 'Thiago Herrera', title: 'Presidente' },
  people: [
    { id: 'thiago', name: 'Thiago Herrera', role: 'Presidente', dept: 'Presidência', avatar: 'Business_Male_01', seat: 'thiago', kind: 'president', color: '#ed3237',
      desc: 'Comanda a Balão da Informática. Define prioridades, acompanha os setores e recebe os reportes dos agentes.', workLabel: 'Despachando na Presidência',
      errands: [{ spot: 'pres.lounge', role: 'text', label: 'Lendo mensagens no celular', icon: '📱', dur: [10, 16], prop: 'phone' }] },
    { id: 'hermes', name: 'Hermes', role: 'Orquestrador-chefe dos agentes', dept: 'Operações', avatar: 'Business_Male_02', seat: 'hermes', kind: 'chief', color: '#06b6d4',
      desc: 'Distribui as tarefas entre os agentes, acompanha a execução e reporta ao Presidente.', workLabel: 'Orquestrando as tarefas',
      errands: [{ spot: 'ops.wall', role: 'listen', clip: 'gestic_thoughtful_01', label: 'Acompanhando a central de orquestração', icon: '🖥️', dur: [10, 16] }, { spot: 'ops.t1', role: 'text', label: 'Disparando tarefas pelo celular', icon: '📱', dur: [9, 14], prop: 'phone' }] },
    { id: 'vendas', name: 'Agente de Vendas', role: 'Vendas · Bling ERP e CRM', dept: 'Vendas & Atendimento', avatar: 'Business_Male_06', seat: 'vendas', kind: 'head', color: '#10b981',
      desc: 'Cuida dos pedidos, do estoque e do catálogo, e acompanha o time de atendimento.', workLabel: 'Acompanhando pedidos e estoque',
      errands: [{ spot: 'vendas.board', role: 'present', label: 'Revisando as metas no quadro', icon: '📊', dur: [10, 16], speaking: true }, { spot: 'vendas.printer', role: 'docs', label: 'Conferindo pedidos impressos', icon: '🧾', dur: [9, 14] }] },
    { id: 'mercado', name: 'Agente de Mercado', role: 'Inteligência de preços', dept: 'Inteligência de Mercado', avatar: 'Business_Male_05', seat: 'mercado', kind: 'head', color: '#f59e0b',
      desc: 'Acompanha os preços da concorrência e avisa sobre as margens antes de cada orçamento.', workLabel: 'Comparando preços da concorrência',
      errands: [{ spot: 'mercado.tv', role: 'listen', clip: 'gestic_thoughtful_01', label: 'Analisando o monitor de preços', icon: '📈', dur: [10, 16] }, { spot: 'mercado.board', role: 'present', label: 'Anotando margens no quadro', icon: '📝', dur: [9, 14] }] },
    { id: 'criativo', name: 'Agente Criativo', role: 'Estúdio de artes e vídeos', dept: 'Estúdio Criativo', avatar: 'Male_Adult_04', seat: 'criativo', kind: 'head', color: '#d946ef',
      desc: 'Produz as artes, os cartazes e os vídeos das campanhas da loja.', workLabel: 'Criando artes da campanha',
      errands: [{ spot: 'criativo.photo', role: 'workMid', label: 'Fotografando o PC Gamer no estúdio', icon: '📸', dur: [10, 16] }, { spot: 'criativo.posters', role: 'listen', clip: 'gestic_thoughtful_01', label: 'Revisando os cartazes', icon: '🎨', dur: [8, 13] }] },
    { id: 'ti', name: 'Agente de TI', role: 'Infraestrutura · VPS e deploy', dept: 'TI & Servidores', avatar: 'Business_Male_07', seat: 'ti', kind: 'head', color: '#3b82f6',
      desc: 'Mantém os servidores, os containers e o deploy do site e do WhatsApp no ar.', workLabel: 'Monitorando os servidores',
      errands: [{ spot: 'ti.rack', role: 'workMid', label: 'Verificando os racks de servidores', icon: '🗄️', dur: [10, 17] }, { spot: 'ti.bench', role: 'workStand', label: 'Montando máquina na bancada', icon: '🛠️', dur: [10, 16] }] },
    { id: 'financeiro', name: 'Agente Financeiro', role: 'Pagamentos · PIX e cobranças', dept: 'Financeiro', avatar: 'Business_Female_03', seat: 'financeiro', kind: 'head', color: '#14b8a6',
      desc: 'Gera as cobranças, confere os comprovantes e acompanha os recebimentos.', workLabel: 'Conferindo recebimentos',
      errands: [{ spot: 'fin.files', role: 'docs', label: 'Consultando os arquivos', icon: '🗂️', dur: [9, 15] }] },
    { id: 'julia', name: 'JUL.IA', role: 'Vendedora digital', dept: 'Vendas & Atendimento', avatar: 'Business_Female_04', seat: 'julia', kind: 'staff', color: '#10b981',
      desc: 'Atende os clientes da loja pelo WhatsApp.', workLabel: 'Atendendo clientes no WhatsApp',
      errands: [{ spot: 'vendas.t1', role: 'text', label: 'Respondendo cliente no celular', icon: '📱', dur: [9, 14], prop: 'phone' }, { spot: 'vendas.printer', role: 'docs', label: 'Pegando um orçamento impresso', icon: '🧾', dur: [8, 12] }] },
    { id: 'vitoria', name: 'VITOR.IA', role: 'Prospecção', dept: 'Vendas & Atendimento', avatar: 'Business_Female_01', seat: 'vitoria', kind: 'staff', color: '#10b981',
      desc: 'Busca novos clientes e abre as primeiras conversas.', workLabel: 'Prospectando novos clientes',
      errands: [{ spot: 'vendas.t2', role: 'text', label: 'Enviando mensagens de prospecção', icon: '📱', dur: [9, 14], prop: 'phone' }, { spot: 'vendas.board', role: 'present', label: 'Atualizando a lista de contatos', icon: '📋', dur: [8, 13] }] },
    { id: 'claudia', name: 'CLAUD.IA', role: 'Cobrança e reativação', dept: 'Vendas & Atendimento', avatar: 'Business_Female_02', seat: 'claudia', kind: 'staff', color: '#10b981',
      desc: 'Cobra pendências e reativa clientes que pararam de comprar.', workLabel: 'Fazendo cobranças e reativações',
      errands: [{ spot: 'vendas.printer', role: 'docs', label: 'Conferindo boletos', icon: '🧾', dur: [8, 13] }, { spot: 'vendas.t1', role: 'text', label: 'Reativando um cliente', icon: '📱', dur: [9, 14], prop: 'phone' }] },
    { id: 'maria', name: 'MAR.IA', role: 'Análise', dept: 'Vendas & Atendimento', avatar: 'Female_Adult_15', seat: 'maria', kind: 'staff', color: '#10b981',
      desc: 'Analisa as conversas e os resultados do atendimento.', workLabel: 'Analisando os atendimentos',
      errands: [{ spot: 'vendas.board', role: 'present', label: 'Apresentando a análise do dia', icon: '📊', dur: [9, 14], speaking: true }, { spot: 'vendas.t2', role: 'docs', label: 'Lendo o relatório', icon: '📄', dur: [8, 13] }] },
    { id: 'recepcao', name: 'Recepção', role: 'Atendimento na entrada', dept: 'Recepção', avatar: 'Female_Adult_02', seat: 'recepcao', kind: 'reception', color: '#ed3237',
      desc: 'Recebe quem chega e encaminha para o setor certo.', workLabel: 'Atendendo na recepção',
      errands: [{ spot: 'recepcao.wait', role: 'idle', label: 'Organizando a sala de espera', icon: '🪴', dur: [8, 12] }] },
  ],
};
