import {
  CrmEtiqueta,
  CrmProdutoCatalogo,
  CrmRespostaRapida,
  CrmVendedor,
  KanbanColumn,
} from "@/types/crm";

export const RESPOSTAS_BASE: CrmRespostaRapida[] = [
  {
    id: 1,
    titulo: "Boas-vindas",
    texto: "Olá! 😄 Tudo bem? Aqui é o Balão da Informática. Como posso te ajudar hoje?",
    categoria: "Saudações",
  },
  {
    id: 2,
    titulo: "Formas de pagamento",
    texto: "Aceitamos PIX (CNPJ 34.397.947/0001-08), cartão e boleto. Pagando no Pix você garante 10% de desconto imediato! 😉",
    categoria: "Pagamento",
  },
  {
    id: 3,
    titulo: "Pagamento PIX",
    texto: "Para pagar via PIX: Chave CNPJ: 34.397.947/0001-08 (Balão da Informática). Envie o comprovante aqui rapidinho que já separamos seu pedido! ✅",
    categoria: "Pagamento",
  },
  {
    id: 4,
    titulo: "Endereço da loja",
    texto: "📍 Balão da Informática Castelo\nRua Santo Antonio Claret, 241 – Castelo – Campinas/SP\nVenha nos visitar, temos estacionamento próprio e testamos tudo na bancada! 😉",
    categoria: "Loja",
  },
  {
    id: 5,
    titulo: "Horário de funcionamento",
    texto: "🕒 Segunda a sexta: 08h30 às 18h\nSábado: 09h às 13h\nEstamos online e também realizamos entregas rápidas na região de Campinas!",
    categoria: "Loja",
  },
  {
    id: 6,
    titulo: "Telefone / WhatsApp",
    texto: "📲 WhatsApp: (19) 98118-8090\n☎️ Loja Física: (19) 3255-1661\nPode chamar a qualquer momento!",
    categoria: "Loja",
  },
  {
    id: 7,
    titulo: "Site da loja",
    texto: "🌐 Acesse nosso site oficial: www.balao.info\nLá você encontra nosso catálogo completo de hardware, notebooks e PCs Gamer!",
    categoria: "Loja",
  },
  {
    id: 8,
    titulo: "Assistência técnica",
    texto: "🔧 Sim! Somos referência em assistência técnica e reparo especializado em computadores, notebooks e linha Apple (iPhone/Mac). Me conta qual o defeito que já te passo uma estimativa!",
    categoria: "Assistência",
  },
  {
    id: 9,
    titulo: "Upgrade de PC",
    texto: "⚡ Trabalhamos com upgrade completo de PC: SSD NVMe, memória RAM, placa de vídeo RTX e processadores. Me diz o modelo do seu equipamento que indico a melhor opção!",
    categoria: "Hardware",
  },
  {
    id: 10,
    titulo: "PC Gamer",
    texto: "🎮 Monte seu PC Gamer com a gente! Me passa seu orçamento aproximado e quais jogos você pretende rodar que monto a melhor configuração custo-benefício na hora!",
    categoria: "PC Gamer",
  },
  {
    id: 11,
    titulo: "Consultar estoque",
    texto: "🔍 Me diz o produto que você procura (marca/modelo) que confirmo o estoque físico e o valor exato no sistema agora mesmo!",
    categoria: "Atendimento",
  },
  {
    id: 12,
    titulo: "Nota fiscal",
    texto: "🧾 Sim, emitimos Nota Fiscal Eletrônica (NF-e) em todas as vendas para CPF e CNPJ, com garantia total!",
    categoria: "Atendimento",
  },
  {
    id: 13,
    titulo: "Garantia",
    texto: "🛡️ Todos os nossos produtos e serviços acompanham garantia com nota fiscal e suporte técnico dedicado na nossa loja física do Castelo.",
    categoria: "Atendimento",
  },
  {
    id: 14,
    titulo: "Trocas/devoluções",
    texto: "📦 Garantia e troca conforme o CDC. Se o produto apresentar qualquer inconformidade, nossa bancada técnica resolve com máxima agilidade!",
    categoria: "Atendimento",
  },
  {
    id: 15,
    titulo: "Entrega Campinas e região",
    texto: "🚚 Atendemos Campinas, Valinhos, Vinhedo, Sumaré, Paulínia e região via motoboy express/Uber Flash ou retirada imediata no balcão da loja Castelo. Me passa seu CEP!",
    categoria: "Entrega",
  },
  {
    id: 16,
    titulo: "Montagem/limpeza",
    texto: "🛠️ Fazemos montagem premium com cable management e limpeza preventiva com troca de pasta térmica de alta condutividade. Agende seu horário com a gente!",
    categoria: "Assistência",
  },
  {
    id: 17,
    titulo: "Retorno/aguardando",
    texto: "⏰ Estou verificando com nossa bancada/estoque e já te retorno aqui mesmo! Só um instante por gentileza. 😉",
    categoria: "Atendimento",
  },
  {
    id: 18,
    titulo: "Agradecimento/encerramento",
    texto: "😊 Muito obrigado pelo contato com o Balão da Informática! Qualquer dúvida é só chamar por aqui. Tenha um excelente dia! 🎈",
    categoria: "Atendimento",
  },
];

export const ETIQUETAS_BASE: CrmEtiqueta[] = [
  { id: 1, nome: "Cliente Quente", cor: "#d93025" },
  { id: 2, nome: "Interessado", cor: "#ffb300" },
  { id: 3, nome: "Cliente Fiel", cor: "#0f9d58" },
  { id: 4, nome: "Pendente de Pagamento", cor: "#1a73e8" },
  { id: 5, nome: "Entregue", cor: "#7b1fa2" },
  { id: 6, nome: "Assistência Técnica", cor: "#00897b" },
];

export const KANBAN_COLUNAS_BASE: KanbanColumn[] = [
  { id: "novos", nome: "Novos Leads", cor: "#3b82f6" },
  { id: "atendimento", nome: "Em Atendimento", cor: "#8b5cf6" },
  { id: "orcamento", nome: "Orçamento Enviado", cor: "#f59e0b" },
  { id: "negociacao", nome: "Em Negociação", cor: "#ec4899" },
  { id: "aguardando_pgto", nome: "Aguardando Pix / Pgto", cor: "#06b6d4" },
  { id: "ganho", nome: "Venda Fechada / Ganho", cor: "#10b981" },
  { id: "pos_venda", nome: "Pós-Venda & Garantia", cor: "#6366f1" },
  { id: "perdido", nome: "Perdido / Sem Retorno", cor: "#64748b" },
];

export const VENDEDORES_BASE: CrmVendedor[] = [
  {
    id: 1,
    nome: "Wendell",
    cargo: "Especialista em PC Gamer & Montagem",
    telefone: "(19) 98118-8090",
    assinatura: "Atenciosamente,\n*Wendell* — Balão da Informática\n📱 (19) 98118-8090",
  },
  {
    id: 2,
    nome: "Carlos",
    cargo: "Consultor de Hardware & Upgrades",
    telefone: "(19) 99122-3344",
    assinatura: "Abraços,\n*Carlos* — Consultoria Técnica Balão\n📍 Balão Castelo Campinas",
  },
  {
    id: 3,
    nome: "Mariana",
    cargo: "Especialista Apple & Mac",
    telefone: "(19) 99233-4455",
    assinatura: "Atenciosamente,\n*Mariana* — Assistência Especializada Apple Balão",
  },
  {
    id: 4,
    nome: "Suporte Balão",
    cargo: "Atendimento Geral",
    telefone: "(19) 98118-8090",
    assinatura: "Equipe Balão da Informática\n🌐 www.balao.info | ☎️ (19) 3255-1661",
  },
];

export const PRODUTOS_CATALOGO_BASE: CrmProdutoCatalogo[] = [
  {
    id: "prod-1",
    nome: "PC Gamer Balão Ryzen 5 5600 + RTX 4060 8GB + 16GB + SSD 1TB NVMe",
    preco: 4390,
    custo: 3490,
    margem: 25.8,
    fornecedor: "Estoque Balão",
    precoFormatado: "R$ 4.390,00",
    categoria: "PC Gamer",
    imagem: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=500&auto=format&fit=crop&q=80",
    specs: ["Ryzen 5 5600", "RTX 4060 8GB", "16GB DDR4 3200MHz", "SSD 1TB M.2", "Fonte 600W 80 Plus"],
  },
  {
    id: "prod-2",
    nome: "Placa de Vídeo ASUS Dual GeForce RTX 4070 Super 12GB GDDR6X",
    preco: 4499,
    custo: 3750,
    margem: 20,
    fornecedor: "Distribuidora Oficial",
    precoFormatado: "R$ 4.499,00",
    categoria: "Hardware",
    imagem: "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=500&auto=format&fit=crop&q=80",
    specs: ["12GB GDDR6X", "DLSS 3.5", "Ray Tracing", "Dual Fan"],
  },
  {
    id: "prod-3",
    nome: "Notebook Dell Inspiron Intel Core i5 16GB SSD 512GB Tela 15.6 Full HD",
    preco: 3299,
    custo: 2690,
    margem: 22.6,
    fornecedor: "Dell Brasil",
    precoFormatado: "R$ 3.299,00",
    categoria: "Notebooks",
    imagem: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500&auto=format&fit=crop&q=80",
    specs: ["Intel Core i5", "16GB RAM", "SSD 512GB NVMe", "Windows 11 Home"],
  },
  {
    id: "prod-4",
    nome: "SSD Kingston NV2 1TB M.2 2280 PCIe 4.0 NVMe Leitura 3500MB/s",
    preco: 439,
    custo: 310,
    margem: 41.6,
    fornecedor: "Kingston",
    precoFormatado: "R$ 439,00",
    categoria: "Armazenamento",
    imagem: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=500&auto=format&fit=crop&q=80",
    specs: ["1TB", "PCIe 4.0 NVMe", "Até 3.500MB/s"],
  },
  {
    id: "prod-5",
    nome: "Assistência Técnica Apple: Troca de Tela / Bateria iPhone com Garantia",
    preco: 390,
    custo: 180,
    margem: 116.6,
    fornecedor: "Bancada Apple",
    precoFormatado: "R$ 390,00",
    categoria: "Serviços Apple",
    imagem: "https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?w=500&auto=format&fit=crop&q=80",
    specs: ["Peças Homologadas", "Garantia 6 Meses", "Troca Express"],
  },
  {
    id: "prod-6",
    nome: "Monitor Gamer 24 Pol. IPS 165Hz 1ms Full HD FreeSync Balão",
    preco: 799,
    custo: 590,
    margem: 35.4,
    fornecedor: "Estoque Balão",
    precoFormatado: "R$ 799,00",
    categoria: "Periféricos",
    imagem: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500&auto=format&fit=crop&q=80",
    specs: ["Painel IPS", "165Hz", "1ms", "HDMI e DP"],
  },
];
