import {
  CrmLead,
  CrmMessage,
  CrmSeller,
  CrmTag,
  FunnelStage,
  QuickReplyTemplate,
  ScheduledMessage,
  BalãoProductCatalogItem,
} from "@/types/crm";

export const CRM_STAGES: FunnelStage[] = [
  {
    id: "new_lead",
    title: "1. Novos Leads / WhatsApp",
    shortTitle: "Novos",
    color: "#3b82f6",
    badgeBg: "bg-blue-500/10 text-blue-400 border-blue-500/20",
    borderColor: "border-blue-500",
    description: "Clientes que acabaram de chamar no WhatsApp do Balão",
  },
  {
    id: "first_contact",
    title: "2. Em Atendimento / Triagem",
    shortTitle: "Atendimento",
    color: "#8b5cf6",
    badgeBg: "bg-purple-500/10 text-purple-400 border-purple-500/20",
    borderColor: "border-purple-500",
    description: "Vendedor conversando e entendendo a necessidade de hardware/serviço",
  },
  {
    id: "budget_sent",
    title: "3. Orçamento Enviado",
    shortTitle: "Orçamento",
    color: "#f59e0b",
    badgeBg: "bg-amber-500/10 text-amber-400 border-amber-500/20",
    borderColor: "border-amber-500",
    description: "Proposta de PC, peça ou serviço enviada no WhatsApp",
  },
  {
    id: "in_negotiation",
    title: "4. Em Negociação",
    shortTitle: "Negociação",
    color: "#ec4899",
    badgeBg: "bg-pink-500/10 text-pink-400 border-pink-500/20",
    borderColor: "border-pink-500",
    description: "Ajustando condições, desconto à vista ou itens adicionais",
  },
  {
    id: "awaiting_payment",
    title: "5. Aguardando Pagamento / Pix",
    shortTitle: "Pgto / Pix",
    color: "#06b6d4",
    badgeBg: "bg-cyan-500/10 text-cyan-400 border-cyan-500/20",
    borderColor: "border-cyan-500",
    description: "Chave Pix ou link gerado aguardando comprovante",
  },
  {
    id: "won",
    title: "6. Venda Fechada / Ganho",
    shortTitle: "Ganho",
    color: "#10b981",
    badgeBg: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
    borderColor: "border-emerald-500",
    description: "Venda concluída e retirada/entregue em Campinas",
  },
  {
    id: "post_sale",
    title: "7. Pós-Venda & Garantia",
    shortTitle: "Pós-Venda",
    color: "#6366f1",
    badgeBg: "bg-indigo-500/10 text-indigo-400 border-indigo-500/20",
    borderColor: "border-indigo-500",
    description: "Acompanhamento de entrega, satisfação ou suporte técnico",
  },
  {
    id: "lost",
    title: "8. Perdido / Sem Retorno",
    shortTitle: "Perdido",
    color: "#64748b",
    badgeBg: "bg-slate-500/10 text-slate-400 border-slate-500/20",
    borderColor: "border-slate-500",
    description: "Lead desistiu ou não respondeu após follow-up",
  },
];

export const CRM_TAGS: CrmTag[] = [
  { id: "vip", name: "VIP / Frequente", color: "#eab308", bgColor: "bg-yellow-500/15 text-yellow-300 border-yellow-500/30" },
  { id: "pcgamer", name: "PC Gamer", color: "#ef4444", bgColor: "bg-red-500/15 text-red-300 border-red-500/30" },
  { id: "apple", name: "Apple / Mac", color: "#a855f7", bgColor: "bg-purple-500/15 text-purple-300 border-purple-500/30" },
  { id: "notebook", name: "Notebook / Upgrade", color: "#3b82f6", bgColor: "bg-blue-500/15 text-blue-300 border-blue-500/30" },
  { id: "assistencia", name: "Assistência / Reparo", color: "#f97316", bgColor: "bg-orange-500/15 text-orange-300 border-orange-500/30" },
  { id: "retirada", name: "Retira Loja Castelo", color: "#10b981", bgColor: "bg-emerald-500/15 text-emerald-300 border-emerald-500/30" },
  { id: "urgente", name: "Alta Prioridade", color: "#f43f5e", bgColor: "bg-rose-500/15 text-rose-300 border-rose-500/30" },
  { id: "corporativo", name: "Empresa / PJ", color: "#06b6d4", bgColor: "bg-cyan-500/15 text-cyan-300 border-cyan-500/30" },
];

export const CRM_SELLERS: CrmSeller[] = [
  {
    id: "wendell",
    name: "Wendell",
    role: "Especialista em PC Gamer & Montagem",
    avatar: "W",
    phone: "(19) 98118-8090",
  },
  {
    id: "carlos",
    name: "Carlos",
    role: "Consultor de Hardware & Upgrades",
    avatar: "C",
    phone: "(19) 99122-3344",
  },
  {
    id: "mariana",
    name: "Mariana",
    role: "Especialista Apple & Mac Reparos",
    avatar: "M",
    phone: "(19) 99233-4455",
  },
  {
    id: "suporte",
    name: "Suporte Geral",
    role: "Atendimento Balão Castelo",
    avatar: "B",
    phone: "(19) 98118-8090",
  },
];

export const BALAO_QUICK_REPLIES: QuickReplyTemplate[] = [
  {
    id: "saudacao_padrao",
    title: "👋 Saudação Inicial Balão",
    category: "saudacoes",
    shortcut: "/ola",
    message: "Olá, {primeiro_nome}! {saudacao}! Aqui é o {vendedor} do *Balão da Informática* de Campinas. Como posso te ajudar hoje? Está procurando algum PC Gamer, peça para upgrade ou serviço de assistência?",
  },
  {
    id: "pix_desconto",
    title: "💳 Desconto Pix 10% + Chave",
    category: "pix",
    shortcut: "/pix",
    message: "Excelente escolha, {primeiro_nome}! Pagando no *Pix*, você garante *10% de desconto imediato* no Balão!\n\n💰 Valor final com desconto: *R$ {valor}*\n🔑 Chave Pix (CNPJ / Telefone Balão): *{chave_pix}*\n\nAssim que fizer o pagamento, envie o comprovante por aqui que já separamos seu pedido!",
  },
  {
    id: "loja_castelo",
    title: "📍 Endereço & Horário Loja Castelo",
    category: "loja",
    shortcut: "/loja",
    message: "Nossa loja física em Campinas fica no bairro Castelo:\n\n📍 *Balão da Informática Castelo*\nEndereço: Rua Santo Antonio Claret, 241 - Castelo, Campinas - SP\n⏰ Horário: Segunda a Sexta das 08h30 às 18h | Sábados das 09h às 13h\n🚗 Estacionamento gratuito no local e testamos tudo na hora!",
  },
  {
    id: "orcamento_pc_gamer",
    title: "🎮 Orçamento PC Gamer Personalizado",
    category: "orcamento",
    shortcut: "/pcgamer",
    message: "Fala {primeiro_nome}! Montei aqui a configuração recomendada para o que você precisa:\n\n🖥️ *PC Gamer Balão High Performance*\n• Processador: AMD Ryzen 5 5600X\n• Placa de Vídeo: NVIDIA GeForce RTX 4060 8GB GDDR6\n• Memória: 16GB (2x8GB) DDR4 3200MHz RGB\n• Armazenamento: SSD NVMe 1TB M.2 Ultra Rápido\n• Fonte: 600W 80 Plus Bronze PFC Ativo\n• Gabinete Gamer com 4 Coolers RGB e Vidro Temperado\n\n💵 *Preço Especial à vista no Pix:* R$ 4.390,00\n💳 Ou em até 12x no cartão de crédito\n\nTodos os PCs saem com Windows 11 instalado, montagem premium com cable management e 1 ano de garantia com suporte técnico do Balão!",
  },
  {
    id: "assistencia_apple",
    title: "🍏 Assistência Especializada Apple",
    category: "assistencia",
    shortcut: "/apple",
    message: "Olá, {primeiro_nome}! Realizamos manutenção e reparo especializado em toda a linha Apple (iPhone, MacBook, iPad e iMac) aqui no Balão Castelo:\n\n🔧 Troca de telas originais e baterias homologadas\n🔧 Reparo de placa mãe e conectores\n🔧 Upgrade de SSD e recuperação de dados macOS\n\nRealizamos diagnóstico e orçamento gratuito no balcão em até 2 horas. Pode trazer na nossa loja hoje?",
  },
  {
    id: "manutencao_notebook",
    title: "💻 Limpeza & Troca Pasta Térmica",
    category: "assistencia",
    shortcut: "/manutencao",
    message: "Oi {primeiro_nome}! O serviço de *Limpeza Preventiva + Troca de Pasta Térmica de Alta Condutividade (Prata)* para notebook inclui:\n\n✔️ Desmontagem e desobstrução completa do cooler/dissipador\n✔️ Aplicação de pasta térmica premium (Artic Silver ou Thermalright)\n✔️ Limpeza interna e desoxidação de contatos\n✔️ Teste de estresse térmico e benchmark\n\n⏳ Tempo de execução: No mesmo dia ou 24h\n💰 Valor promocional: R$ 149,00 à vista.",
  },
  {
    id: "followup_24h",
    title: "⏰ Follow-up Orçamento (24h)",
    category: "followup",
    shortcut: "/retorno",
    message: "Olá, {primeiro_nome}! Tudo bem? Passando para saber se conseguiu avaliar o orçamento que te passei daquele *{produto}*. Ainda temos as peças separadas para você com a condição especial de Pix. Ficou alguma dúvida técnica ou sobre pagamento?",
  },
  {
    id: "retirada_pronta",
    title: "📦 Pedido Pronto para Retirada",
    category: "loja",
    shortcut: "/pronto",
    message: "Ótima notícia, {primeiro_nome}! Seu pedido está pronto, montado e testado aqui na nossa bancada da unidade Castelo Campinas. Você já pode passar para retirar ou solicitar entrega expressa via Uber Flash / Motoboy. Te aguardamos!",
  },
];

export const BALAO_FEATURED_PRODUCTS: BalãoProductCatalogItem[] = [
  {
    id: "pc-gamer-rtx4060",
    name: "PC Gamer Balão Ryzen 5 5600 + RTX 4060 8GB + 16GB + SSD 1TB",
    price: 4390,
    formattedPrice: "R$ 4.390,00",
    category: "PC Gamer",
    image: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=500&auto=format&fit=crop&q=80",
    slug: "pc-gamer-ryzen-rtx4060",
    specs: ["Ryzen 5 5600", "RTX 4060 8GB", "16GB DDR4", "SSD 1TB M.2 NVMe", "Fonte 600W 80 Plus"],
    badge: "Mais Vendido",
  },
  {
    id: "gpu-rtx-4070-super",
    name: "Placa de Vídeo ASUS Dual GeForce RTX 4070 Super 12GB GDDR6X",
    price: 4499,
    formattedPrice: "R$ 4.499,00",
    category: "Hardware",
    image: "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=500&auto=format&fit=crop&q=80",
    slug: "placa-de-video-rtx-4070-super",
    specs: ["12GB GDDR6X", "DLSS 3.5", "Ray Tracing", "Dual Fan Silencioso"],
    badge: "10% OFF Pix",
  },
  {
    id: "notebook-dell-i5",
    name: "Notebook Dell Inspiron Intel Core i5 16GB SSD 512GB Tela 15.6 Full HD",
    price: 3299,
    formattedPrice: "R$ 3.299,00",
    category: "Notebooks",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500&auto=format&fit=crop&q=80",
    slug: "notebook-dell-inspiron-i5-16gb",
    specs: ["Core i5 12ª Ger.", "16GB RAM", "SSD 512GB NVMe", "Windows 11"],
    badge: "Pronta Entrega",
  },
  {
    id: "ssd-kingston-nvme-1tb",
    name: "SSD Kingston NV2 1TB M.2 2280 PCIe 4.0 NVMe Leitura 3500MB/s",
    price: 439,
    formattedPrice: "R$ 439,00",
    category: "Armazenamento",
    image: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=500&auto=format&fit=crop&q=80",
    slug: "ssd-kingston-nv2-1tb",
    specs: ["1TB", "PCIe 4.0 NVMe", "Até 3.500MB/s Leitura"],
    badge: "Upgrade Rápido",
  },
  {
    id: "servico-reparo-apple",
    name: "Assistência Técnica Apple: Troca de Tela / Bateria iPhone com Garantia",
    price: 390,
    formattedPrice: "R$ 390,00",
    category: "Serviços Apple",
    image: "https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?w=500&auto=format&fit=crop&q=80",
    slug: "assistencia-apple-campinas",
    specs: ["Peças Homologadas", "Troca em 1 Hora", "Garantia 6 Meses"],
    badge: "Express",
  },
  {
    id: "monitor-gamer-165hz",
    name: "Monitor Gamer 24 Pol. IPS 165Hz 1ms Full HD FreeSync Balão",
    price: 799,
    formattedPrice: "R$ 799,00",
    category: "Periféricos",
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500&auto=format&fit=crop&q=80",
    slug: "monitor-gamer-165hz-ips",
    specs: ["Painel IPS", "165Hz", "1ms", "HDMI / DisplayPort"],
    badge: "Gamer",
  },
];

const now = Date.now();
const hour = 3600 * 1000;
const day = 24 * hour;

export const INITIAL_SEED_LEADS: CrmLead[] = [
  {
    id: "lead-1",
    chatId: "5519981112233@c.us",
    name: "Lucas Fernandes Gamer",
    phone: "(19) 98111-2233",
    displayNumber: "+55 19 98111-2233",
    email: "lucas.gamer@gmail.com",
    city: "Campinas - Cambuí",
    preferredBranch: "Loja Castelo",
    stage: "budget_sent",
    dealValue: 4390,
    tags: ["pcgamer", "vip", "urgente"],
    assignedSellerId: "wendell",
    unreadCount: 1,
    lastMessageBody: "Gostei muito da config com a RTX 4060. Vocês conseguem colocar 32GB de RAM se eu fechar no Pix hoje?",
    lastMessageTimestamp: now - 15 * 60 * 1000,
    notes: [
      {
        id: "note-1",
        author: "Wendell",
        text: "Cliente quer jogar Warzone e GTA RP em 144Hz. Mostrei o PC Ryzen 5 5600 + RTX 4060. Prometi verificar upgrade de 32GB de RAM.",
        timestamp: now - 30 * 60 * 1000,
      },
    ],
    productOfInterest: "PC Gamer Balão Ryzen 5 5600 + RTX 4060",
    createdAt: now - 1 * day,
    updatedAt: now - 15 * 60 * 1000,
  },
  {
    id: "lead-2",
    chatId: "5519992224455@c.us",
    name: "Camila Duarte (MacBook Pro)",
    phone: "(19) 99222-4455",
    displayNumber: "+55 19 99222-4455",
    email: "camila.arq@duartedesign.com.br",
    city: "Campinas - Taquaral",
    preferredBranch: "Loja Castelo",
    stage: "in_negotiation",
    dealValue: 850,
    tags: ["apple", "assistencia", "retirada"],
    assignedSellerId: "mariana",
    unreadCount: 0,
    lastMessageBody: "Perfeito, Mariana! Vou levar o MacBook aí na loja no começo da tarde para vocês abrirem a OS.",
    lastMessageTimestamp: now - 45 * 60 * 1000,
    notes: [
      {
        id: "note-2",
        author: "Mariana",
        text: "MacBook Pro M1 2020 aquecendo muito e bateria com aviso de manutenção. Orçamento de troca de bateria + higienização térmica R$ 850.",
        timestamp: now - 2 * hour,
      },
    ],
    productOfInterest: "Manutenção Apple & Troca de Bateria",
    createdAt: now - 2 * day,
    updatedAt: now - 45 * 60 * 1000,
  },
  {
    id: "lead-3",
    chatId: "5519983335566@c.us",
    name: "Roberto Mendes (Tech Soluções)",
    phone: "(19) 98333-5566",
    displayNumber: "+55 19 98333-5566",
    email: "roberto@techsolucoes.com.br",
    document: "12.345.678/0001-99",
    city: "Campinas - Barão Geraldo",
    preferredBranch: "Loja Castelo",
    stage: "awaiting_payment",
    dealValue: 6598,
    tags: ["corporativo", "notebook", "retirada"],
    assignedSellerId: "carlos",
    unreadCount: 0,
    lastMessageBody: "Chave Pix recebida! O financeiro da empresa está aprovando agora de manhã e já mando o comprovante.",
    lastMessageTimestamp: now - 3 * hour,
    notes: [
      {
        id: "note-3",
        author: "Carlos",
        text: "Compra corporativa de 2x Notebooks Dell i5 para a equipe de desenvolvimento. Emitir NF-e com o CNPJ informado.",
        timestamp: now - 4 * hour,
      },
    ],
    productOfInterest: "2x Notebook Dell Inspiron i5 16GB",
    createdAt: now - 3 * day,
    updatedAt: now - 3 * hour,
  },
  {
    id: "lead-4",
    chatId: "5519974446677@c.us",
    name: "Matheus Oliveira (Upgrade RTX)",
    phone: "(19) 97444-6677",
    displayNumber: "+55 19 97444-6677",
    email: "matheus.olv@hotmail.com",
    city: "Valinhos - SP",
    preferredBranch: "Loja Castelo",
    stage: "won",
    dealValue: 4499,
    tags: ["pcgamer", "vip"],
    assignedSellerId: "wendell",
    unreadCount: 0,
    lastMessageBody: "Venda concluída! Placa ASUS RTX 4070 Super retirada e instalada com sucesso na máquina.",
    lastMessageTimestamp: now - 6 * hour,
    notes: [
      {
        id: "note-4",
        author: "Wendell",
        text: "Cliente pagou no Pix R$ 4.499. Feita instalação e teste de benchmark na bancada do Balão Castelo. Cliente muito satisfeito.",
        timestamp: now - 6 * hour,
      },
    ],
    productOfInterest: "ASUS Dual RTX 4070 Super 12GB",
    createdAt: now - 4 * day,
    updatedAt: now - 6 * hour,
  },
  {
    id: "lead-5",
    chatId: "5519995557788@c.us",
    name: "Dra. Juliana Prado",
    phone: "(19) 99555-7788",
    displayNumber: "+55 19 99555-7788",
    email: "juliana.prado@clinica.med.br",
    city: "Campinas - Nova Campinas",
    preferredBranch: "Loja Castelo",
    stage: "new_lead",
    dealValue: 1200,
    tags: ["urgente", "assistencia", "notebook"],
    assignedSellerId: null,
    unreadCount: 2,
    lastMessageBody: "Olá! Meu notebook parou de ligar e tenho relatórios urgentes da clínica. Vocês conseguem fazer orçamento rápido?",
    lastMessageTimestamp: now - 8 * 60 * 1000,
    notes: [],
    productOfInterest: "Reparo emergencial notebook",
    createdAt: now - 10 * 60 * 1000,
    updatedAt: now - 8 * 60 * 1000,
  },
  {
    id: "lead-6",
    chatId: "5519986668899@c.us",
    name: "Gabriel Santos (CS2 & Valorant)",
    phone: "(19) 98666-8899",
    displayNumber: "+55 19 98666-8899",
    email: "gabriel.cs2@outlook.com",
    city: "Sumaré - SP",
    preferredBranch: "Loja Castelo",
    stage: "first_contact",
    dealValue: 1238,
    tags: ["pcgamer", "retirada"],
    assignedSellerId: "wendell",
    unreadCount: 0,
    lastMessageBody: "Vocês tem monitor 165Hz pronta entrega no Castelo e um SSD de 1TB pra eu buscar hoje?",
    lastMessageTimestamp: now - 1 * hour,
    notes: [
      {
        id: "note-6",
        author: "Wendell",
        text: "Combo Monitor 165Hz IPS + SSD Kingston 1TB NVMe. Total R$ 1.238 no Pix.",
        timestamp: now - 50 * 60 * 1000,
      },
    ],
    productOfInterest: "Monitor 165Hz + SSD Kingston 1TB",
    createdAt: now - 5 * hour,
    updatedAt: now - 1 * hour,
  },
  {
    id: "lead-7",
    chatId: "5519977779900@c.us",
    name: "André Farias (iMac Design)",
    phone: "(19) 97777-9900",
    displayNumber: "+55 19 97777-9900",
    email: "andre@fariasdesign.com",
    city: "Paulínia - SP",
    preferredBranch: "Loja Castelo",
    stage: "post_sale",
    dealValue: 1850,
    tags: ["apple", "vip"],
    assignedSellerId: "mariana",
    unreadCount: 0,
    lastMessageBody: "O iMac ficou excelente com o SSD novo! Muito obrigado pelo atendimento rápido da equipe do Balão.",
    lastMessageTimestamp: now - 1 * day,
    notes: [
      {
        id: "note-7",
        author: "Mariana",
        text: "Upgrade de SSD 1TB + Instalação limpa macOS Ventura em iMac 27. Entregue e testado.",
        timestamp: now - 1 * day,
      },
    ],
    productOfInterest: "Upgrade iMac 27 SSD 1TB",
    createdAt: now - 5 * day,
    updatedAt: now - 1 * day,
  },
];

export const INITIAL_SEED_MESSAGES: CrmMessage[] = [
  {
    id: "msg-1-1",
    chatId: "5519981112233@c.us",
    from: "5519981112233@c.us",
    body: "Boa tarde! Vi o anúncio de vocês no site do Balão sobre os PCs Gamer montados.",
    direction: "in",
    timestamp: now - 50 * 60 * 1000,
    contactName: "Lucas Fernandes Gamer",
    status: "read",
  },
  {
    id: "msg-1-2",
    chatId: "5519981112233@c.us",
    from: "balao",
    body: "Olá, Lucas! Boa tarde! Aqui é o Wendell do Balão da Informática de Campinas. Perfeito! O PC com Ryzen 5 5600 + RTX 4060 8GB está saindo por R$ 4.390,00 no Pix com 10% de desconto.",
    direction: "out",
    timestamp: now - 40 * 60 * 1000,
    status: "read",
  },
  {
    id: "msg-1-3",
    chatId: "5519981112233@c.us",
    from: "5519981112233@c.us",
    body: "Gostei muito da config com a RTX 4060. Vocês conseguem colocar 32GB de RAM se eu fechar no Pix hoje?",
    direction: "in",
    timestamp: now - 15 * 60 * 1000,
    contactName: "Lucas Fernandes Gamer",
    status: "delivered",
  },
];

export const INITIAL_SCHEDULED_MESSAGES: ScheduledMessage[] = [
  {
    id: "sched-1",
    leadId: "lead-1",
    leadName: "Lucas Fernandes Gamer",
    phone: "(19) 98111-2233",
    message: "Fala Lucas! Consegui liberar o upgrade dos 32GB de RAM para o seu PC Gamer com a RTX 4060 mantendo a condição do Pix! Posso fechar seu pedido para montagem?",
    sendAt: new Date(now + 2 * hour).toISOString(),
    status: "pending",
    sellerId: "wendell",
    createdAt: now - 10 * 60 * 1000,
  },
  {
    id: "sched-2",
    leadId: "lead-2",
    leadName: "Camila Duarte (MacBook Pro)",
    phone: "(19) 99222-4455",
    message: "Oi Camila! Nossa bancada técnica da Apple já está com os componentes reservados para receber seu MacBook Pro hoje na unidade Castelo!",
    sendAt: new Date(now + 4 * hour).toISOString(),
    status: "pending",
    sellerId: "mariana",
    createdAt: now - 30 * 60 * 1000,
  },
];
