import { createRequire } from 'module';
const require = createRequire('/opt/npm-tools/node_modules/');
const { chromium } = require('playwright');
const [w, h, out, extra] = [+(process.argv[2] || 390), +(process.argv[3] || 800), process.argv[4] || 'build/mob.jpg', process.argv[5] || ''];
const browser = await chromium.launch({ args: ['--use-gl=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const ctx = await browser.newContext({ viewport: { width: w, height: h }, deviceScaleFactor: 1, hasTouch: true, isMobile: true });
const page = await ctx.newPage();
page.on('console', m => { const t = m.text(); if (!/GPU stall/.test(t)) console.log('[page]', m.type(), t.slice(0, 300)); }); page.on('pageerror', e => console.log('[pageerror]', e.message));
page.on('requestfailed', r => console.log('[failed]', r.url()));
const t0 = Date.now();
await page.goto('http://localhost:8766/3d/?nointro&shot&pr=1&hora=tarde' + extra);
await page.waitForFunction('window.__office && document.body.classList.contains("ready")', null, { timeout: 300000 });
console.log('ready in', Date.now() - t0, 'ms');
const info = await page.evaluate(() => { const o = window.__office; o.renderer.setAnimationLoop(null); o.ff(15); o.still(2); return { q: o.st.quality, touch: document.body.classList.contains('touch'), lamps: o.world.lamps.filter(l => l.visible).length, tex: o.renderer.info.memory.textures }; });
console.log(JSON.stringify(info));
await page.waitForTimeout(400); await page.screenshot({ path: out, type: 'jpeg', quality: 85 });
await page.evaluate(() => { const o = window.__office; o.setMode('fpv', { force: true }); o.still(2); }); await page.waitForTimeout(400); await page.screenshot({ path: out.replace('.jpg', '_fpv.jpg'), type: 'jpeg', quality: 85 });
await page.evaluate(() => { const o = window.__office; o.setMode('overview', { force: true }); o.ui.select(o.sim.byId.get('thiago')); o.still(2); }); await page.waitForTimeout(400); await page.screenshot({ path: out.replace('.jpg', '_card.jpg'), type: 'jpeg', quality: 85 });
await browser.close();
